### ISSUE TITLE
Error while migrating

### ISSUE THREAD

**Issue by antonin-a** [VictorDM/taiga2jira#2]
Hello, 

I don't know if this project is still active but it would be really useful for us. I manage to set parameter and access to Taiga & Jira but I have the following error during the migration:

`
INFO Migrating sprints to Jira
INFO Taiga getting project support sprints
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 1569.33it/s]
INFO Searching board 291 sprint '20181201-20181231 Done'
INFO Getting board 291 sprints
INFO Creating sprint 20181201-20181231 Done
INFO Sprint created: 431 # 20181201-20181231 Done
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    main()
  File "main.py", line 34, in main
    migrator.sprints_to_jira(taiga_api, jira_api, taiga_project_key, jira_board, logger)
  File "/home/cloud/taiga2jira/migrator.py", line 116, in sprints_to_jira
    taiga_user_stories = taiga_api.get_sprint_stories(taiga_project_key, sprint.get("id")).get("user_stories")
  File "/home/cloud/taiga2jira/api/taigaAPI.py", line 111, in get_sprint_stories
    json.get('user_stories').append(self._create_user_story_json(user_story, project_key))
  File "/home/cloud/taiga2jira/api/taigaAPI.py", line 79, in _create_user_story_json
    json_tasks = self._get_user_story_tasks(project_key, user_story.ref).get('tasks')
  File "/home/cloud/taiga2jira/api/taigaAPI.py", line 69, in _get_user_story_tasks
    'finished_date': taiga_to_date_time(task.finished_date),
  File "/home/cloud/taiga2jira/api/utils.py", line 23, in taiga_to_date_time
    return datetime.datetime.strptime(str_date_time, datetime_format)
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 346, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: T09:21:07.234Z
`

When checking the log file: 
`
INFO Starting migration from Taiga to Jira
INFO Connecting to Taiga
INFO Connecting to Taiga OK
INFO Getting Jira boards
INFO Migrating sprints to Jira
INFO Taiga getting project support sprints
INFO Searching board 291 sprint '20181201-20181231 Done'
INFO Getting board 291 sprints
INFO Creating sprint 20181201-20181231 Done
INFO Sprint created: 431 # 20181201-20181231 Done
`

Any idea ? Thank you by advance !

**Comment by VictorDM** [comment]
Hi.

It looks like a date time format problem. Could you run it from fix/date-time branch and send me the output of the date string?
